entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"

  websecure:
    address: ":443"

api:
  dashboard: true
  insecure: true

certificatesResolvers:
  lets-encrypt:
    acme:
      email: "admin@performance.mu"
      storage: "acme.json"
      tlsChallenge: {}

providers:
  docker:
    watch: true
    network: "web"

  file:
    filename: "traefik_dynamic.yml"
